---
- name: Prepare all nodes
  hosts: all_nodes
  become: True
  vars_files:
    - secrets.yml  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  tags:
    - apt_cache

- name: Configure all nodes (timezone, ufw, fail2ban)
  hosts: all_nodes
  become: True
  vars_files:
    - secrets.yml
  roles:
    - common
  tags:
    - common

- name: Configure MySQL Master-Master
  hosts: mysql_nodes
  become: True
  vars_files:
    - secrets.yml
  roles:
    - mysql
  tags:
    - mysql

- name: Сonfigure HAProxy
  hosts: haproxy_node
  become: True
  vars_files:
    - secrets.yml
  roles:
    - haproxy
  tags:
    - haproxy

- name: Install Zabbix server (Docker)
  hosts: zabbix_node
  become: True
  vars_files:
    - secrets.yml
  roles:
    - { role: docker, tags: docker }
    - { role: zabbix-server, tags: zabbix-server }
  tags:
    - docker-zabbix

- name: Install Zabbix-agent2
  hosts: all_nodes
  become: True
  vars_files:
    - secrets.yml
  roles:
    - zabbix-agent
  tags:
    - zabbix-agent